# Generated by Django 3.2.8 on 2021-11-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211103_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefix',
            field=models.TextField(max_length=5),
        ),
    ]
